from setuptools import setup, find_packages

setup(
    name="news-transport",
    version="1.0.0",
    description="新闻搬运系统 - 自动汇总国内热点新闻，智能处理后发布到海外平台",
    author="OpenClaw",
    packages=find_packages(),
    install_requires=[
        'requests>=2.31.0',
        'beautifulsoup4>=4.12.2',
        'lxml>=4.9.3',
        'selenium>=4.15.2',
        'webdriver-manager>=4.0.1',
        'jieba>=0.42.1',
        'sumy>=0.11.0',
        'openai>=1.3.5',
        'transformers>=4.35.2',
        'torch>=2.1.0',
        'googletrans==4.0.0-rc1',
        'pandas>=2.1.3',
        'sqlalchemy>=2.0.23',
        'redis>=5.0.1',
        'flask>=3.0.0',
        'flask-sqlalchemy>=3.1.1',
        'flask-login>=0.6.3',
        'wtforms>=3.1.1',
        'apscheduler>=3.10.4',
        'schedule>=1.2.0',
        'tweepy>=4.14.0',
        'python-telegram-bot>=20.7',
        'python-dotenv>=1.0.0',
        'loguru>=0.7.2',
        'pydantic>=2.5.0',
        'tenacity>=8.2.3',
        'fake-useragent>=1.4.0',
        'click>=8.1.7',
    ],
    entry_points={
        'console_scripts': [
            'news-transport = main:cli',
        ],
    },
    classifiers=[
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.9',
)
